import { Theme } from "../types";

export const colors = {
  light: {
    background: "#F8FCFF",
    surface: "#FFFFFF",
    primary: "#46beed",
    text: "#1a1a1a",
    textSecondary: "#6B7280",
    border: "#E5E7EB",
    inputBackground: "#F3F4F6",
    messageBubbleOwn: "#46beed",
    messageBubbleOther: "#F0F9FF",
    messageTextOwn: "#FFFFFF",
    messageTextOther: "#1a1a1a",
    statusPending: "#FFA500",
    statusSent: "#4CAF50",
    statusRead: "#9C27B0",
    statusFailed: "#F44336",
    headerBackground: "#46beed",
    headerText: "#FFFFFF",
    primaryLight: "#7CCEF5",
    primaryDark: "#2BA5DB",
    accent: "#FF6B6B",
    success: "#4CAF50",
    warning: "#FFA500",
    error: "#F44336",
    errorLight: "#FFEBEE",
    disabled: "#D1D5DB",
  },
  dark: {
    background: "#0F1419",
    surface: "#1C2128",
    primary: "#46beed",
    text: "#FFFFFF",
    textSecondary: "#9CA3AF",
    border: "#374151",
    inputBackground: "#2D3748",
    messageBubbleOwn: "#46beed",
    messageBubbleOther: "#2D3748",
    messageTextOwn: "#FFFFFF",
    messageTextOther: "#FFFFFF",
    statusPending: "#FF9F0A",
    statusSent: "#32D74B",
    statusRead: "#BF5AF2",
    statusFailed: "#FF453A",
    headerBackground: "#1C2128",
    headerText: "#FFFFFF",
    primaryLight: "#7CCEF5",
    primaryDark: "#2BA5DB",
    accent: "#FF6B6B",
    success: "#32D74B",
    warning: "#FF9F0A",
    error: "#FF453A",
    errorLight: "#2D1B1B",
    disabled: "#4B5563",
  },
};

export const getThemeColors = (theme: Theme) => colors[theme];
